config/routes.rb
CarApp::Application.routes.draw do
  devise_for :users
  root :to => "cars#index"

  resources :cars do
     resources :maintenances
     get '/refuels/graphs' => 'refuels#graphs', :as => 'graphs'
     resources :refuels
  end

#  resources :users do
#    resources :cars
#  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ActiveRecord::Base
   belongs_to :user
   has_many :maintenances
   has_many :refuels
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.accessible_by(current_ability)

    respond_to do |format|
	format.html
	format.json { render json: @cars.to_json(:include => [:maintenances, :refuels]) }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car.to_json(:include => [:maintenances, :refuels]) }
    end
  end

  # GET /cars/new
  def new
    @car = current_user.cars.build
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car.user_id = current_user.id

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new', notice: 'Failure' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:Make, :Model, :Cost, :Description, :vin, :License_Plate, :year, :in_inventory, :user_id)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :Make, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Make, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Model, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Model, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Cost, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vin, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vin, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :License_Plate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :License_Plate, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :year, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :year, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :in_inventory, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :in_inventory, :class => 'checkbox' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cars_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Make) %></th>
      <th><%= model_class.human_attribute_name(:Model) %></th>
      <th><%= model_class.human_attribute_name(:Cost) %></th>
      <th><%= model_class.human_attribute_name(:Description) %></th>
      <th><%= model_class.human_attribute_name(:vin) %></th>
      <th><%= model_class.human_attribute_name(:License_Plate) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:in_inventory) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= link_to car.id, car_path(car) %></td>
        <td><%= car.Make %></td>
        <td><%= car.Model %></td>
        <td><%= car.Cost %></td>
        <td><%= car.Description %></td>
        <td><%= car.vin %></td>
        <td><%= car.License_Plate %></td>
        <td><%= car.year %></td>
        <td><%= car.in_inventory %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_car_path(car), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      car_path(car),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_car_path,
            :class => 'btn btn-primary' %>

app/views/cars/new.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Make) %>:</strong></dt>
  <dd><%= @car.Make %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Model) %>:</strong></dt>
  <dd><%= @car.Model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Cost) %>:</strong></dt>
  <dd><%= @car.Cost %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Description) %>:</strong></dt>
  <dd><%= @car.Description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vin) %>:</strong></dt>
  <dd><%= @car.vin %></dd>
  <dt><strong><%= model_class.human_attribute_name(:License_Plate) %>:</strong></dt>
  <dd><%= @car.License_Plate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @car.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:in_inventory) %>:</strong></dt>
  <dd><%= @car.in_inventory %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cars_path, :class => 'btn' %>
  <%= link_to t('.maintenance', :default => t("helpers.links.maintenances")),
              car_maintenances_path(@car), :class => 'btn' %>
  <%= link_to t('.refuel', :default => t("helpers.links.refuels")),
              car_refuels_path(@car), :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_car_path(@car), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              car_path(@car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>